FROM mcr.microsoft.com/devcontainers/dotnet:8.0

# Install additional OS packages
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
    tree \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

# [Optional] Uncomment if you want to install more global node packages
# RUN su vscode -c "dotnet tool install -g other-tool-you-want"